### ISSUE TITLE
Log enrychnemt returns empty

### ISSUE THREAD

**Issue by DavidGershony** [block-core/blockcore-nodes#19]
The logs are returned as is from the receipt with no added logs for our NFT contract computing.

**Comment by dangershony** [comment]
This is the part of the code that is failing and it seems very odd that the account is null here 
https://github.com/block-core/blockcore-nodes/blob/master/CRS/Cirrus.Node/Controllers/IndexerContractsController.cs#L87

Perhaps @rowandh can shade some light on this? 
How can the account be null if we use the `PostState` form the receipt?
