### ISSUE TITLE
Fix IMPL reference node

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-nodes#4]
- The IMPL reference node does not start sync.

Reference the changes done here, and/or contact the team behind it: 

https://github.com/impleum/ImpleumBitcoinFullNode

**Comment by thecrypt0hunter** [comment]
The team have been contacted and are planning to review the reference node.

**Comment by sondreb** [comment]
The team has provided Blockcore with an implementation of IMPLX, that is published and fully working.
